apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: default
type: Opaque
data:
  # Substitua pelo base64 das suas credenciais do Google Cloud
  credentials.json: <BASE64_DAS_CREDENCIAIS_GCP> 