spring:
  application:
    name: cadastro-cliente-consumer
  
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:cadastro_cliente};encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  
  cloud:
    gcp:
      pubsub:
        project-id: ${GCP_PROJECT_ID:your-project-id}
        credentials:
          location: ${GCP_CREDENTIALS_LOCATION:classpath:gcp-credentials.json}
        subscriber:
          retry:
            initial-retry-delay: 1s
            max-retry-delay: 10s
            max-attempts: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ebury.cadastrocliente: DEBUG
    org.springframework.cloud.gcp.pubsub: DEBUG
    org.springframework.integration: DEBUG

server:
  port: 8081
  servlet:
    context-path: / 