spring:
  application:
    name: cadastro-cliente-consumer
  
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:cadastro_cliente};encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  
  cloud:
    gcp:
      pubsub:
        project-id: ${GCP_PROJECT_ID:your-project-id}
        credentials:
          location: ${GCP_CREDENTIALS_LOCATION:classpath:gcp-credentials.json}
        subscriber:
          retry:
            initial-retry-delay: 1s
            max-retry-delay: 10s
            max-attempts: 5
          # Configurações de ACK deadline
          ack-deadline: 30s
          # Configurações de pull
          max-ack-extension-period: 60s
          # Configurações de concorrência
          parallel-pull-count: 1
          max-concurrent-ack-count: 100

# Configurações customizadas para retry
app:
  pubsub:
    retry:
      max-attempts: 3
      delay-ms: 1000
      backoff-multiplier: 2.0
    dead-letter:
      enabled: true
      topic: cliente-cadastro-dlq
      subscription: cliente-cadastro-dlq-sub

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ebury.cadastrocliente: DEBUG
    org.springframework.cloud.gcp.pubsub: DEBUG
    org.springframework.integration: DEBUG

server:
  port: 8081
  servlet:
    context-path: / 